
package io.elastic.dnb.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "NewsAndMediaProduct", targetNamespace = "http://services.dnb.com/NewsAndMediaProductServiceV2.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NewsAndMediaProduct {


    /**
     * 
     * @param parameter
     * @return
     *     returns io.elastic.dnb.jaxws.OrderProductResponse
     * @throws TransactionFault
     */
    @WebMethod(operationName = "OrderProduct", action = "http://services.dnb.com/NewsAndMediaProductService/V3.0/OrderProduct")
    @WebResult(name = "OrderProductResponse", targetNamespace = "http://services.dnb.com/NewsAndMediaProductServiceV2.0", partName = "parameter")
    public OrderProductResponse orderProduct(
        @WebParam(name = "OrderProductRequest", targetNamespace = "http://services.dnb.com/NewsAndMediaProductServiceV2.0", partName = "parameter")
        OrderProductRequest parameter)
        throws TransactionFault
    ;

    /**
     * 
     * @param parameter
     * @return
     *     returns io.elastic.dnb.jaxws.RetrieveProductResponse
     * @throws TransactionFault
     */
    @WebMethod(operationName = "RetrieveProduct", action = "http://services.dnb.com/NewsAndMediaProductService/V3.0/RetrieveProduct")
    @WebResult(name = "RetrieveProductResponse", targetNamespace = "http://services.dnb.com/NewsAndMediaProductServiceV2.0", partName = "parameter")
    public RetrieveProductResponse retrieveProduct(
        @WebParam(name = "RetrieveProductRequest", targetNamespace = "http://services.dnb.com/NewsAndMediaProductServiceV2.0", partName = "parameter")
        RetrieveProductRequest parameter)
        throws TransactionFault
    ;

}
