
package io.elastic.dnb.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NewsAndMediaProductService", targetNamespace = "http://services.dnb.com/NewsAndMediaProductServiceV2.0", wsdlLocation = "file:/C:/Java/Elastic/GetCompanyNews/src/main/resources/V3.0/NewsAndMediaProductService.wsdl")
public class NewsAndMediaProductService
    extends Service
{

    private final static URL NEWSANDMEDIAPRODUCTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(io.elastic.dnb.jaxws.NewsAndMediaProductService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = io.elastic.dnb.jaxws.NewsAndMediaProductService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Java/Elastic/GetCompanyNews/src/main/resources/V3.0/NewsAndMediaProductService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Java/Elastic/GetCompanyNews/src/main/resources/V3.0/NewsAndMediaProductService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NEWSANDMEDIAPRODUCTSERVICE_WSDL_LOCATION = url;
    }

    public NewsAndMediaProductService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NewsAndMediaProductService() {
        super(NEWSANDMEDIAPRODUCTSERVICE_WSDL_LOCATION, new QName("http://services.dnb.com/NewsAndMediaProductServiceV2.0", "NewsAndMediaProductService"));
    }

    /**
     * 
     * @return
     *     returns NewsAndMediaProduct
     */
    @WebEndpoint(name = "NewsAndMediaProductServiceEndPoint")
    public NewsAndMediaProduct getNewsAndMediaProductServiceEndPoint() {
        return super.getPort(new QName("http://services.dnb.com/NewsAndMediaProductServiceV2.0", "NewsAndMediaProductServiceEndPoint"), NewsAndMediaProduct.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NewsAndMediaProduct
     */
    @WebEndpoint(name = "NewsAndMediaProductServiceEndPoint")
    public NewsAndMediaProduct getNewsAndMediaProductServiceEndPoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.dnb.com/NewsAndMediaProductServiceV2.0", "NewsAndMediaProductServiceEndPoint"), NewsAndMediaProduct.class, features);
    }

}
