
package io.elastic.dnb.jaxws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "TransactionResult", targetNamespace = "http://services.dnb.com/TransactionFaultV2.0")
public class TransactionFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TransactionResult2 faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TransactionFault(String message, TransactionResult2 faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TransactionFault(String message, TransactionResult2 faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: io.elastic.dnb.jaxws.TransactionResult2
     */
    public TransactionResult2 getFaultInfo() {
        return faultInfo;
    }

}
